version: "3"
services:
  app:
    container_name: spreadsheet-express
    restart: always
    build: .
    ports:
      - "8000:8000"
    links:
      - mongo
  mongo:
    container_name: spreadsheet-mongo
    image: mongo
    ports:
      - "27017:27017"